spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pm_auth_db
    username: postgres
    password: 4422

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
logging:
  level:
    com.pm.authservice: DEBUG
    org.springframework.security: DEBUG
    org.springframework.mail: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

app:
  jwt:
    secret: MyDevSecretKeyThatIsAtLeast32CharactersLongForDevelopment123
    access-token-expiration-minutes: 60 # 1 hour
  frontend:
    url: http://localhost:3000