server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:pm_expense_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:4422}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false

logging:
  level:
    com.pm.expenseservice: INFO
    org.springframework.security: WARN
  file:
    name: /app/logs/expense-service.log

app:
  jwt:
    secret: ${JWT_SECRET}
  auth-service:
    url: ${AUTH_SERVICE_URL:http://auth-service:8084}